# Job 2: Run tests (dependent on build job)
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job runs successfully before 'test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      # Run the tests
      - name: Run tests with Maven
        run: mvn test
      # Generate code coverage report with JaCoCo
      - name: Generate Code Coverage Report
        run: mvn jacoco:report
