name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
   # Job 1: Build the project
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B clean compile
        
  checkstyle:
    runs-on: ubuntu-latest
    name: checkstyle
    steps:
      - uses: actions/checkout@v3
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: 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
          reporter: github-pr-review
          checkstyle_config: google_checks.xml
# Job 2: Run tests (dependent on build job)
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job runs successfully before 'test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      # Run the tests
      - name: Run tests with Maven
        run: mvn test
      # Generate code coverage report with JaCoCo
      - name: Generate Code Coverage Report
        run: mvn jacoco:report
          
